Repository appsignal/appsignal-python, pull requests merged in 2023-05, with the labels that each got.

#25 Auto cancel builds on Semaphore CI
  .semaphore/semaphore.yml
Labels: dev happiness

#26 Make all the config options optional fields
  src/appsignal/config.py
Labels: chore

#24 Move resource attributes to private env var config
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
  tests/test_config.py
Labels: chore

#28 Add boolean config options
  src/appsignal/client.py
  src/appsignal/config.py
  tests/test_client.py
  tests/test_config.py
Labels: chore

#31 Add config options of the list type
  src/appsignal/config.py
  tests/test_config.py
Labels: enhancement

#33 Add string config options
  src/appsignal/config.py
  tests/test_config.py
Labels: enhancement

#35 Add ca_file_path config option
  src/appsignal/config.py
  tests/test_config.py
Labels: enhancement

#37 Add log_path config option
  src/appsignal/config.py
  tests/test_config.py
Labels: enhancement

#40 Add default `ca_file_path` certificates
  src/appsignal/config.py
  src/appsignal/resources/cacert.pem
Labels: chore

#38 Implement install command
  pyproject.toml
  src/appsignal/cli.py
  src/appsignal/config.py
  tests/test_cli.py
Labels: enhancement

#44 Add `version_scheme` to Mono config
  mono.yml
Labels: chore

#46 Config refactor part 2
  src/appsignal/config.py
  tests/test_config.py
  tests/test_opentelemetry.py
Labels: chore

#47 Add convenience method to fetch config options
  src/appsignal/config.py
  tests/test_config.py
Labels: chore

#52 Add request_headers config option
  src/appsignal/client.py
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
  tests/test_client.py
  tests/test_config.py
Labels: enhancement

#54 Fix package for Python 3.8
  .semaphore/semaphore.yml
  pyproject.toml
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
  src/scripts/build_hook.py
  tests/test_config.py
  tests/test_opentelemetry.py
Labels: bug

#55 Lock Python versions in the project
  .python-version
Labels: chore

#53 Drop Python 3.7 support
  pyproject.toml
Labels: chore

#50 Add internal logger
  src/appsignal/client.py
  src/appsignal/config.py
  tests/test_client.py
Labels: enhancement

#58 Fix log path failure log message
  src/appsignal/config.py
Labels: bug

#59 Add demo command
  src/appsignal/cli.py
Labels: feature

#60 Add Flask integration
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
Labels: enhancement

#61 Fix test suite state
  conftest.py
  src/appsignal/agent.py
  tests/test_client.py
Labels: bug

#63 Make sure agent is stopped before every test
  conftest.py
Labels: bug

#64 Check for dependencies when installing
  src/appsignal/cli.py
Labels: enhancement
