Repository appsignal/appsignal-python, pull requests merged in 2023-07, with the labels that each got.

#93 Fix stop_agent fixture
  conftest.py
Labels: bug

#94 Update OpenTelemetry HTTP exporter path
  src/appsignal/opentelemetry.py
Labels: chore

#91 Refactoring: turn agent wrapper into a singleton
  conftest.py
  src/appsignal/agent.py
  src/appsignal/client.py
  tests/test_client.py
Labels: chore

#95 Annotate everything
  pyproject.toml
  src/appsignal/cli/base.py
  src/appsignal/cli/demo.py
  src/appsignal/cli/install.py
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
  src/scripts/build_all.py
  src/scripts/build_hook.py
  tests/test_opentelemetry.py
Labels: chore

#98 Make mypy configuration more strict
  pyproject.toml
Labels: chore

#99 Make ruff configuration more strict
  pyproject.toml
  src/appsignal/cli/install.py
  src/appsignal/client.py
  src/appsignal/config.py
  src/scripts/build_all.py
  src/scripts/build_hook.py
  tests/test_opentelemetry.py
Labels: chore

#100 Make Config classmethods staticmethods instead
  src/appsignal/config.py
Labels: chore

#96 Restore literal typing for instrumentations
  src/appsignal/opentelemetry.py
  tests/test_opentelemetry.py
Labels: chore

#104 Add `RENDER_GIT_COMMIT` support
  .changesets/use-render_git_commit-as-revision.md
  src/scripts/agent.py
Labels: chore

#105 Bump agent to 32590eb
  .changesets/bump-agent-to-32590eb.md
  src/scripts/agent.py
Labels: enhancement

#107 Report total CPU usage host metric for VMs
  .changesets/report-total-cpu-usage-metric-for-vms.md
  src/scripts/agent.py
Labels: enhancement

#110 Bump agent to 6bec691
  .changesets/bump-agent-to-6bec691.md
  src/scripts/agent.py
Labels: enhancement
