Repository appsignal/appsignal-python, pull requests merged in 2023-06, with the labels that each got.

#65 Add query params to Flask spans
  src/appsignal/opentelemetry.py
Labels: enhancement

#66 Validate Push API key when installing
  src/appsignal/cli.py
  tests/test_cli.py
Labels: enhancement

#73 Allow custom agent builds
  README.md
  mono.yml
  pyproject.toml
  src/scripts/build_hook.py
Labels: dev happiness

#74 Update agent to version 8cb4ef2
  .changesets/bump-agent-to-8cb4ef2.md
  src/scripts/agent.py
Labels: bug

#68 Load file/initial config options source load
  src/appsignal/config.py
  tests/test_config.py
Labels: chore

#77 Bump agent to 91f1a7c
  .changesets/bump-agent-to-91f1a7c.md
  src/scripts/agent.py
Labels: chore

#78 Add and update project files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SUPPORT.md
Labels: chore

#79 Refactor CLI file
  pyproject.toml
  src/appsignal/cli/base.py
  src/appsignal/cli/command.py
  src/appsignal/cli/demo.py
  src/appsignal/cli/install.py
  tests/test_cli.py
Labels: dev happiness, enhancement

#81 Bump agent to version ff454dc
  .changesets/add-support-for-asgi-frameworks.md
  src/scripts/agent.py
Labels: enhancement

#82 Annotate None return type
  src/appsignal/agent.py
  src/appsignal/cli/command.py
  src/appsignal/cli/demo.py
  src/appsignal/cli/install.py
  src/appsignal/client.py
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
  src/scripts/build_hook.py
Labels: enhancement

#83 Mypy config
  pyproject.toml
  src/appsignal/client.py
Labels: enhancement
