Repository appsignal/appsignal-python, pull requests merged in 2023-10, with the labels that each got.

#135 Update tag value types to support int, float, bool
  src/appsignal/metrics.py
  tests/test_metrics.py
Labels: enhancement

#137 Bump agent to e8207c1
  .changesets/bump-agent-to-e8207c1.md
  src/scripts/agent.py
Labels: enhancement

#139 Bump package classifiers to stable
  pyproject.toml
Labels: chore

#143 Demo CLI tests tweaks
  src/appsignal/cli/demo.py
  tests/cli/test_install.py
Labels: chore

#146 Add demo CLI test and remove validate output
  .changesets/validate-config-before-starting.md
  src/appsignal/cli/demo.py
  src/appsignal/config.py
  tests/cli/test_demo.py
  tests/test_config.py
Labels: chore

#147 Add demo CLI --environment option
  .changesets/add---environment-cli-option-to-demo-cli-tool.md
  src/appsignal/cli/command.py
  src/appsignal/cli/demo.py
  src/appsignal/cli/install.py
  src/appsignal/config.py
  tests/cli/test_demo.py
Labels: enhancement

#149 Load __appsignal__.py file when found in demo CLI
  .changesets/load-__appsignal__-py-file-in-demo-cli.md
  src/appsignal/cli/demo.py
  src/appsignal/cli/install.py
  tests/cli/test_demo.py
  tests/cli/test_install.py
Labels: enhancement

#152 Update substring assertions in tests
  tests/cli/test_demo.py
  tests/cli/test_diagnose.py
Labels: chore

#153 Add set_sql_body tracing helper
  .changesets/add-set_sql_body-tracing-helper.md
  .changesets/bump-agent-8260fa1.md
  src/appsignal/__init__.py
  src/appsignal/tracing.py
  src/scripts/agent.py
  tests/test_tracing.py
Labels: enhancement

#154 Refactor Push API key validation in install CLI
  src/appsignal/cli/install.py
  tests/cli/test_install.py
Labels: chore

#151 Load __appsignal__.py file when found in diagnose
  .changesets/fix-agent-diagnostic-report-in-diagnose-cli-tool.md
  .changesets/load-__appsignal__-py-file-in-demo-cli.md
  src/appsignal/cli/demo.py
  src/appsignal/cli/diagnose.py
  src/appsignal/client.py
  tests/cli/test_demo.py
  tests/cli/test_diagnose.py
Labels: enhancement

#163 Fix push API key validation on installer
  .changesets/fix-push-api-key-validation.md
  src/appsignal/cli/command.py
  src/appsignal/cli/install.py
Labels: bug

#155 Bump package to version 1.0
  .changesets/_release-1-0.md
Labels: chore

#165 Fix the demo samples recognition and use a custom DemoError class
  .changesets/fix-demo-error-and-performance-incidents.md
  .changesets/rename-example-error-reported-by-our-installer-and-demo-clis.md
  src/appsignal/cli/demo.py
Labels: bug

#164 Add push API key message to client file template
  .changesets/add-warning-to-client-file.md
  src/appsignal/cli/install.py
  tests/cli/test_install.py
Labels: chore

#166 Use the `set_error` helper in the demo CLI
  src/appsignal/cli/demo.py
Labels: chore

#167 Update CHANGELOG with link to blog post for v1.0
  CHANGELOG.md
Labels: chore
