Repository appsignal/appsignal-python, pull requests merged in 2023-11, with the labels that each got.

#175 Bump agent to 1dd2a18
  .changesets/bump-agent-1dd2a18.md
  src/scripts/agent.py
Labels: enhancement

#174 Fix demo CLIs samples metadata
  .changesets/fix-demo-samples-metadata.md
  src/appsignal/cli/demo.py
Labels: bug

#177 Bump agent to eec7f7b
  .changesets/cgroups-v2-cpu-stats-normalization.md
  src/scripts/agent.py
Labels: chore

#176 Fix missing platform file error
  .changesets/fix-crash-diagnose-report-platform.md
  pyproject.toml
  src/appsignal/agent.py
  src/appsignal/cli/diagnose.py
  src/scripts/build_hook.py
Labels: bug

#180 Bump agent to aa4daed
  .changesets/fix-method-tag-override.md
  .changesets/improve-requests-spans.md
  .changesets/probes-update.md
  .changesets/remove-extra-http-attributes-django.md
  .changesets/remove-route-tag.md
  .changesets/skip-more-disk-mountpoints.md
  src/scripts/agent.py
Labels: chore
