Repository appsignal/appsignal-python, pull requests merged in 2023-09, with the labels that each got.

#121 Add OpenTelemetry metrics exporter
  .changesets/enable-opentelemetry-metrics-exporter.md
  src/appsignal/opentelemetry.py
Labels: feature

#127 Add metric helpers for counters and gauges
  .changesets/add-counter-metric-helper.md
  .changesets/add-gauge-metric-helper.md
  src/appsignal/metrics.py
  tests/test_metrics.py
Labels: enhancement

#128 Sample data helpers
  .changesets/add-error-helpers.md
  .changesets/add-sample-data-helpers.md
  conftest.py
  src/appsignal/__init__.py
  src/appsignal/opentelemetry.py
  src/appsignal/tracing.py
  tests/test_tracing.py
Labels: enhancement

#132 Export metric helpers in root module
  .changesets/add-counter-metric-helper.md
  .changesets/add-gauge-metric-helper.md
  src/appsignal/__init__.py
  tests/test_metrics.py
Labels: chore
