Repository appsignal/appsignal-python, pull requests merged in 2024-06, with the labels that each got.

#213 Use qualified error type name
  tests/test_tracing.py
Labels: chore

#212 Add noop mode for unsupported systems
  .changesets/add-noop-mode-for-unsupported-systems.md
  src/appsignal/agent.py
  src/appsignal/client.py
  src/scripts/build_hook.py
  src/scripts/platform.py
Labels: chore

#215 Notify changelog repository of new releases
  .github/workflows/create_release_from_tag.yml
Labels: dev happiness

#217 Add support for Pika
  .changesets/add-support-for-pika.md
  src/appsignal/config.py
  src/appsignal/opentelemetry.py
Labels: enhancement, feature

#218 Bump agent to version 0.35.17
  .changesets/add-pika-extractor.md
  src/scripts/agent.py
Labels: chore
